# .github/workflows/deploy.yml
name: Deploy Node.js Application

on:
  push:
    branches:
      - main
    paths:
      - 'server/**'
      - 'content/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build # If you have a build step

    - name: Deploy
      run: npm run deploy # Customize this to your deployment method
      env:
        MY_SECRET: ${{ secrets.MY_SECRET }} 
        # Ensure your deployment method uses this env
